services:
  trivial:
    image: ghcr.io/${GHCR_OWNER:-your-github-user}/scoreboard-bot:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_PATH: /bot/data/database.db
      DISCORD_LOG_PATH: /bot/data/discord.log

    volumes:
      - bot-data:/bot/data

volumes:
  bot-data:
